---
# 1) System update
- name: Update packages cache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

# 2) Check if server needs to be rebooted
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Restart machine
  reboot:
    msg: "Reboot initiated by Ansible"
  when: reboot_required_file.stat.exists == true

- name: Waiting for server to come back after reboot
  wait_for_connection:
    connect_timeout: 300
    delay: 10
  register: reboot_result
  when: reboot_required_file.stat.exists == true

- name: Reboot time
  debug:
    msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."
  when: reboot_required_file.stat.exists == true

# 3) Create sudo admin, add ssh public key and set no password
- name: Create sudo user
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    shell: /bin/bash
    createhome: true
    groups: sudo
    append: yes

- name: Add authorized keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"

- name: Set no password for sudo user
  lineinfile: "dest=/etc/sudoers line='{{ username }}    ALL=(ALL)    NOPASSWD: ALL'"

